version: 1
update_configs:
  # App parts
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    target_branch: "master"
    default_assignees:
      - "eolme"
    default_reviewers:
      - "eolme"
    default_labels:
      - "APP"
      - "DEPS"
    allowed_updates:
      - match:
          dependency_type: "all"
          update_type: "security"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
    version_requirement_updates: "off"
  # API parts
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    target_branch: "master"
    default_assignees:
      - "eolme"
    default_reviewers:
      - "eolme"
    default_labels:
      - "API"
      - "DEPS"
    allowed_updates:
      - match:
          dependency_type: "all"
          update_type: "security"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "semver:minor"
